
import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { Header } from "@/components/layout/Header";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Badge } from "@/components/ui/badge";
import { Switch } from "@/components/ui/switch";
import { Loader2, Plus, Sparkles, FileText, Copy, Trash, Save } from "lucide-react";
import { toast } from "sonner";

interface Template {
    id: number;
    title: string;
    description: string;
    structure: string; // JSON string
    is_public: boolean;
    version: number;
    status: string;
}

export default function Templates() {
    const navigate = useNavigate();

    useEffect(() => {
        const token = localStorage.getItem("token");
        if (!token) {
            navigate("/login");
            return;
        }
    }, [navigate]);
    const [templates, setTemplates] = useState<Template[]>([]);
    const [isLoading, setIsLoading] = useState(false);
    const [isDialogOpen, setIsDialogOpen] = useState(false);

    // Form State
    const [title, setTitle] = useState("");
    const [description, setDescription] = useState("");
    const [items, setItems] = useState<string[]>([""]);
    const [isPublic, setIsPublic] = useState(false);

    // AI State
    const [aiTopic, setAiTopic] = useState("");
    const [isAiLoading, setIsAiLoading] = useState(false);

    // Fetch Templates
    const fetchTemplates = async () => {
        try {
            const token = localStorage.getItem("token");
            if (!token) return;

            const response = await fetch("/api/v1/templates/", {
                headers: { Authorization: `Bearer ${token}` }
            });

            if (response.ok) {
                const data = await response.json();
                setTemplates(data);
            }
        } catch (error) {
            console.error("Failed to fetch templates", error);
        }
    };

    useEffect(() => {
        fetchTemplates();
    }, []);

    const handleAddItem = () => {
        setItems([...items, ""]);
    };

    const handleUpdateItem = (index: number, value: string) => {
        const newItems = [...items];
        newItems[index] = value;
        setItems(newItems);
    };

    const handleRemoveItem = (index: number) => {
        setItems(items.filter((_, i) => i !== index));
    };

    const handleAiGenerate = async () => {
        if (!aiTopic) return;
        setIsAiLoading(true);
        try {
            const token = localStorage.getItem("token");
            const response = await fetch("/api/v1/templates/suggest-items", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    Authorization: `Bearer ${token}`
                },
                body: JSON.stringify({ topic: aiTopic })
            });

            if (response.ok) {
                const data = await response.json();
                setItems(data.items);
                toast.success("Agenda items generated by AI");
            }
        } catch (error) {
            toast.error("Failed to generate items");
        } finally {
            setIsAiLoading(false);
        }
    };

    const handleSave = async () => {
        if (!title) {
            toast.error("Title is required");
            return;
        }

        const token = localStorage.getItem("token");
        if (!token) {
            toast.error("Please sign in");
            return;
        }

        try {
            const response = await fetch("/api/v1/templates/", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    Authorization: `Bearer ${token}`
                },
                body: JSON.stringify({
                    title,
                    description,
                    structure: JSON.stringify(items.filter(i => i.trim() !== "")),
                    is_public: isPublic
                })
            });

            if (response.ok) {
                toast.success("Template created successfully");
                setIsDialogOpen(false);
                fetchTemplates();
                // Reset form
                setTitle("");
                setDescription("");
                setItems([""]);
                setIsPublic(false);
                setAiTopic("");
            } else {
                toast.error("Failed to create template");
            }
        } catch (error) {
            toast.error("Error creating template");
        }
    };

    return (
        <div className="min-h-screen bg-background">
            <Header />
            <main className="container py-8">
                <div className="flex items-center justify-between mb-8">
                    <div>
                        <h1 className="font-display text-3xl font-bold">Agenda Templates</h1>
                        <p className="text-muted-foreground mt-1">
                            Create and manage reusable meeting agendas
                        </p>
                    </div>
                    <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
                        <DialogTrigger asChild>
                            <Button className="gap-2">
                                <Plus className="h-4 w-4" />
                                Create Template
                            </Button>
                        </DialogTrigger>
                        <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
                            <DialogHeader>
                                <DialogTitle>Create New Template</DialogTitle>
                                <DialogDescription>
                                    Choose how you want to start building your template.
                                </DialogDescription>
                            </DialogHeader>

                            <Tabs defaultValue="scratch" className="w-full">
                                <TabsList className="grid w-full grid-cols-3">
                                    <TabsTrigger value="scratch">From Scratch</TabsTrigger>
                                    <TabsTrigger value="ai">AI Generator</TabsTrigger>
                                    <TabsTrigger value="samples">Samples</TabsTrigger>
                                </TabsList>

                                {/* From Scratch & Shared Form Area */}
                                <div className="mt-4 space-y-4">
                                    <div className="space-y-2">
                                        <Label>Template Title</Label>
                                        <Input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="e.g., Weekly Standup" />
                                    </div>
                                    <div className="space-y-2">
                                        <Label>Description</Label>
                                        <Textarea value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Brief description of when to use this..." />
                                    </div>
                                </div>

                                <TabsContent value="scratch" className="mt-4">
                                    {/* Default simple form, already rendered above */}
                                </TabsContent>

                                <TabsContent value="ai" className="mt-4 space-y-4">
                                    <div className="flex gap-2">
                                        <Input
                                            placeholder="What is this meeting about? (e.g., 'Quarterly Budget Planning')"
                                            value={aiTopic}
                                            onChange={(e) => setAiTopic(e.target.value)}
                                        />
                                        <Button onClick={handleAiGenerate} disabled={isAiLoading}>
                                            {isAiLoading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Sparkles className="h-4 w-4" />}
                                        </Button>
                                    </div>
                                </TabsContent>

                                <TabsContent value="samples" className="mt-4 grid gap-2">
                                    <div className="text-center py-8 text-muted-foreground">
                                        <Sparkles className="h-12 w-12 mx-auto mb-3 opacity-50" />
                                        <p className="text-sm">Use the AI Generator tab to create agenda templates based on your meeting topic.</p>
                                        <p className="text-xs mt-2">Or start from scratch with your own custom items.</p>
                                    </div>
                                </TabsContent>

                                {/* Agenda Builder */}
                                <div className="mt-6">
                                    <div className="flex items-center justify-between mb-2">
                                        <Label>Agenda Items</Label>
                                        <Button variant="ghost" size="sm" onClick={handleAddItem} className="h-8 gap-1">
                                            <Plus className="h-3 w-3" /> Add Item
                                        </Button>
                                    </div>
                                    <div className="space-y-2 max-h-[200px] overflow-y-auto border rounded-md p-2">
                                        {items.map((item, index) => (
                                            <div key={index} className="flex gap-2">
                                                <Input
                                                    value={item}
                                                    onChange={(e) => handleUpdateItem(index, e.target.value)}
                                                    placeholder={`Item ${index + 1}`}
                                                />
                                                <Button variant="ghost" size="icon" onClick={() => handleRemoveItem(index)}>
                                                    <Trash className="h-4 w-4 text-muted-foreground hover:text-destructive" />
                                                </Button>
                                            </div>
                                        ))}
                                    </div>
                                </div>

                                {/* Options / Settings */}
                                <div className="mt-6 pt-4 border-t space-y-4">
                                    <h3 className="font-medium text-sm">Workflow & Settings</h3>
                                    <div className="flex items-center justify-between">
                                        <div className="space-y-0.5">
                                            <Label>Make Public</Label>
                                            <p className="text-xs text-muted-foreground">Visible to all users</p>
                                        </div>
                                        <Switch checked={isPublic} onCheckedChange={setIsPublic} />
                                    </div>
                                    <div className="flex items-center justify-between">
                                        <div className="space-y-0.5">
                                            <Label>Versioning</Label>
                                            <p className="text-xs text-muted-foreground">Auto-increment version (v1)</p>
                                        </div>
                                        <Badge variant="secondary">Active</Badge>
                                    </div>
                                    <div className="flex items-center justify-between">
                                        <div className="space-y-0.5">
                                            <Label>Approval Workflow</Label>
                                            <p className="text-xs text-muted-foreground">Require approval before publishing</p>
                                        </div>
                                        <Badge variant="outline">Disabled (Premium)</Badge>
                                    </div>
                                </div>

                            </Tabs>

                            <DialogFooter className="mt-6">
                                <Button variant="outline" onClick={() => setIsDialogOpen(false)}>Cancel</Button>
                                <Button onClick={handleSave} className="gap-2">
                                    <Save className="h-4 w-4" />
                                    Create Template
                                </Button>
                            </DialogFooter>
                        </DialogContent>
                    </Dialog>
                </div>

                <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
                    {templates.map((template) => (
                        <Card key={template.id}>
                            <CardHeader>
                                <div className="flex justify-between items-start">
                                    <CardTitle>{template.title}</CardTitle>
                                    <Badge variant="secondary">v{template.version}</Badge>
                                </div>
                                <CardDescription>{template.description || "No description provided."}</CardDescription>
                            </CardHeader>
                            <CardContent>
                                <p className="text-sm font-medium mb-2">Agenda Structure:</p>
                                <div className="bg-muted p-3 rounded-md text-sm text-muted-foreground">
                                    <ul className="list-disc list-inside">
                                        {JSON.parse(template.structure).slice(0, 3).map((item: string, i: number) => (
                                            <li key={i}>{item}</li>
                                        ))}
                                        {JSON.parse(template.structure).length > 3 && (
                                            <li className="list-none text-xs mt-1 italic">...and {JSON.parse(template.structure).length - 3} more</li>
                                        )}
                                    </ul>
                                </div>
                            </CardContent>
                            <CardFooter className="flex justify-between text-xs text-muted-foreground">
                                <span>{template.status}</span>
                                <span>{template.is_public ? "Public" : "Private"}</span>
                            </CardFooter>
                        </Card>
                    ))}

                    {templates.length === 0 && (
                        <div className="col-span-full text-center py-12 text-muted-foreground">
                            No templates found. Create one to get started!
                        </div>
                    )}
                </div>
            </main>
        </div>
    );
}
